// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DiceRoller
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("dice_notation")]
        public string DiceNotation { get; set; }

        [JsonProperty("num_dice")]
        public long NumDice { get; set; }

        [JsonProperty("num_sides")]
        public long NumSides { get; set; }

        [JsonProperty("modifier")]
        public long Modifier { get; set; }

        [JsonProperty("rolls")]
        public long[] Rolls { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }

        [JsonProperty("total_with_modifier")]
        public long TotalWithModifier { get; set; }

        [JsonProperty("min_roll")]
        public long MinRoll { get; set; }

        [JsonProperty("max_roll")]
        public long MaxRoll { get; set; }

        [JsonProperty("average_roll")]
        public double AverageRoll { get; set; }

        [JsonProperty("theoretical_min")]
        public long TheoreticalMin { get; set; }

        [JsonProperty("theoretical_max")]
        public long TheoreticalMax { get; set; }

        [JsonProperty("theoretical_average")]
        public double TheoreticalAverage { get; set; }

        [JsonProperty("expression")]
        public string Expression { get; set; }
    }
}
